#!/bin/bash

if [ ! -e "$HOME/.cdmem" ]; then 
    echo $HOME > ~/.cdmem
fi

alias cd='source cd-memo'

if [[ "$(pwd)" != "$HOME" ]]; then
    echo "cd: working directory is already set, ignoring"
    echo "You can still go to last working directory using 'cd --'"
    return
fi

\cd "$(cat ~/.cdmem)" 2> /dev/null

if [ "$?" -ne "0" ]; then
    echo "cd: previous directory ($(cat ~/.cdmem)) is inaccessible"
fi


